# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.

# Нам нужно стригерить на пул и пуш
#
# Для добавления в GoDaddy нужного домена нужно зарегать creadentials в корне репозитория
# и используя метод https://developer.godaddy.com/doc/endpoint/domains#/v1/recordAdd добавить github.ref = 'refs/heads/<branch_name>'


# нужно <branch_name> достать из string и вставить в dns запись вида <branch_name>.<domain_name>
# если ветка main то <branch_name> = muteitapp
# по адресу http://www.godaddy.com/v1/domains/{domain}/records передаем json:  
# [
#   {
#     "data": "string", # Обязательно
#     "name": "string", # Обязательно $domain
#     "port": 0,
#     "priority": 0,
#     "protocol": "string",
#     "service": "string",
#     "ttl": 0,
#     "type": "A", # обязательно 
#     "weight": 0
#   }
# ]

#env:
  # пример переменной: MY_ENV_VAR: ${{ <expression> }} 
  # DOMAIN_NAME: ${{ <expression> }} # получаем из CNAME
  # BRANCH_NAME: ${{ <expression> }} # получаем из github.ref
  # GODADDY_API_CREDANTIAL: ${{ secrets.GODADDY_API_CREDANTIAL }} # зарегать на godaddy и прописать в репозиторий

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
#jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event." #github.event_name - наименование события, например, push
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!" #runner.os - наименование оси сервера, на котором происходит обработка job'a, например, Linux
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}." #github.ref - ветка, с которой мы запушили и github.repository - репозиторий
      - name: Check out repository code #просто имя, может быть любым
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner." #github.repository - репозиторий
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
  
  Check-List-files-in-repository:
    runs-on: macOS-latest
      - name: List files in the repository
      steps:
        run: |
          ls ${{ github.workspace }} 
      - run: echo "🍏 This job's status is ${{ job.status }}." #job.status - статус Job'ы
  