# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.

# Нам нужно стригерить на пул и пуш
#
# Для добавления в GoDaddy нужного домена нужно зарегать creadentials в корне репозитория
# и используя метод https://developer.godaddy.com/doc/endpoint/domains#/v1/recordAdd добавить github.ref = 'refs/heads/<branch_name>'


# нужно <branch_name> достать из string и вставить в dns запись вида <branch_name>.<domain_name>
# если ветка main то <branch_name> = muteitapp
# по адресу http://www.godaddy.com/v1/domains/{domain}/records передаем json:  
# [
#   {
#     "data": "string", # Обязательно
#     "name": "string", # Обязательно $domain
#     "port": 0,
#     "priority": 0,
#     "protocol": "string",
#     "service": "string",
#     "ttl": 0,
#     "type": "A", # обязательно 
#     "weight": 0
#   }
# ]

#env:
  # пример переменной: MY_ENV_VAR: ${{ <expression> }} 
  # DOMAIN_NAME: ${{ <expression> }} # получаем из CNAME
  # BRANCH_NAME: ${{ <expression> }} # получаем из github.ref
  # GODADDY_API_CREDANTIAL: ${{ secrets.GODADDY_API_CREDANTIAL }} # зарегать на godaddy и прописать в репозиторий

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
#job 1 upload file
  job_1:
    name: Ubuntu Job 1
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo Job 1 is done! Congratulations!
          echo Job 1 wrote in file!
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v2
        with:
          name: Job1
          path: job1.txt
   #job 2 summa + 9     
  job_2:
    name: Winodws Job 2
    needs: job_1
    runs-on: windows-latest
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v2
        with:
          name: Job2
      - shell: bash
        run: |
          value=`cat job1.txt`
          expr $value \+ 9 > job1.txt
      - name: Upload math result for job 2
        uses: actions/upload-artifact@v2
        with:
          name: Job2
          path: job1.txt
  
  #Job 3 Display Results
  job_3:
    name: Display results (macOS)
    needs: job_2
    runs-on: macOS-latest
    steps:
      - name: Download math result for job 2
        uses: actions/download-artifact@v2
        with:
          name: Job3
      - name: Print the final result
        shell: bash
        run: |
          value=`cat job1.txt`
          echo The result is $value
  